### ISSUE TITLE
Best answer not displayed properly

### ISSUE THREAD

**Issue by justoverclockl** [FriendsOfFlarum/best-answer#45] opened 2021-06-09 09:00 UTC
Url where u can see the bug:
https://flarum.it/d/130-il-footer-personalizzato-si-sovrappone-alla-sidebar-di-destra

seems that css doesn't work well, can u help me to find a solution?
flarum is up to date to the latest version.
![Immagine 2021-06-09 105954](https://user-images.githubusercontent.com/79002016/121325386-d9c31580-c911-11eb-999b-53ad0145814e.png)

**Comment by imorland** [comment] 2021-06-09 09:18
We have an open PR #44 for this.

It's currently awaiting review, and I'm also trying to further understand the root cause, as locally I don't see the issue. Maybe there's something introduced by another extension, for example as well.

**Comment by imorland** [comment] 2021-06-09 20:11
Fixed in `1.0.1`

**Closed by imorland** 2021-06-09 20:11 UTC
Labels: bug
