### ISSUE TITLE
Unable to reset after removing a best answer

### ISSUE THREAD

**Issue by FoskyM** [FriendsOfFlarum/best-answer#83] opened 2023-08-26 13:15 UTC
## Bug Report

**Current Behavior**
Unable to reset after removing a best answer. 
When I first set it, it works successfully, but if I removed it, I can't set the best answer again because the button disappeared.
I used the devtools and try to fix with failure.

**Environment**
- Flarum version: 1.8.1
- Extension version: 1.3.1
- Webserver: nginx
- PHP version: 8.0.29
- Browser: edge 116

```
Output of "php flarum info", run this in terminal in your Flarum directory.

I don't have permission to run it.
```

**Possible solution(s)**
[extend.php](https://github.com/FoskyM/best-answer/blob/master/extend.php#L80)
I fixed this possible problem in Api as I thought the problem was here but didn't solve it.
![Snipaste_2023-08-26_21-09-40](https://github.com/FriendsOfFlarum/best-answer/assets/39661663/b792348a-75b5-4880-b128-040fadb0d2de)
But then I found it's not the factor.
Because it also controlled by discussion's attribute "canSelectBestAnswer", but I don't know how it determine.
![Snipaste_2023-08-26_21-03-30](https://github.com/FriendsOfFlarum/best-answer/assets/39661663/890725be-a1bb-4450-aeea-1121db5d352a)

**Comment by imorland** [comment] 2024-06-15 10:23
Hello @FoskyM sorry it's taken us so long to pick this report up.

I've added some tests to the extension to check for this scenario [here](https://github.com/FriendsOfFlarum/best-answer/pull/93) but I'm not able to reproduce the problem on the latest version. I will assume that this issue is no longer affecting you, so I'll close this ticket.

Please feel free to re-open if I'm incorrect!

**Closed** 2024-06-15 10:23 UTC
Labels: bug
